### ISSUE TITLE
Video: improve TBT

### ISSUE THREAD

**Issue by paolomoz** [hlxsites/bevespi#189]
Follow up from: https://github.com/hlxsites/bevespi/pull/169

**Comment by dicagno** [comment]
@lansami solved in #322 ?

**Comment by lansami** [comment]
yes, this should be solved, but I think there is space for improvement
the video library is currently loaded with delay, 3.2s after the video block is loaded, this does not mean the script is loaded after the page load.
the script is loaded with defer, it's execution is started after the page load, this will not block the page, but for the user the experience is that they will see a blank space for a short time
I've tried also to use a placeholder and start the download of the library after the user clicks on the placeholder, this increased the page performance, but it was not very user friendly because sometimes the autoplay of the kaltura is not always working.

What I would suggest for improvement would be to set a placeholder for the video, using a image from the doc, and replace the placeholder when the library is loaded and the video is ready, I think this would increase the user experience

**Comment by dicagno** [comment]
fixed in #322
